export const BLOGS = [
  {
    id: 0,
    imgurl: "images/Blog/Saviynt_SFC.png",
    name: "Saviynt",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title:
      "Saviynt Partners with St. Fox to Build a Scalable, Trusted Identity Ecosystem for India",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "Sep 12, 2025",
  },
  {
    id: 1,
    imgurl: "/images/Blog/eraofAI.png",
    name: "Red Teaming LLMs",
    nameBgColor: "bg-[#FCE8F3]  text-[#99154B]",
    title: "Being Human in era of AI",
    icon: "/images/home/man.png",
    subname: "Ranjeet Maske",
    text: "Read more",
    date: "Nov 29, 2024",
  },
  {
    id: 2,
    imgurl: "/images/Blog/Mitigations.png",
    name: "	Red Teaming LLMs",
    nameBgColor: "bg-[#FCE8F3]  text-[#99154B]",
    title: "Prompt Injection - Practical Mitigations",
    icon: "/images/home/man.png",
    subname: "Ranjeet Maske",
    text: "Read more",
    date: "Nov 6, 2024",
  },
  {
    id: 3,
    imgurl: "/images/Blog/Olympics.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title:
      "Cybersecurity Concerns and Preparedness for the Paris 2024 Olympics",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "Aug 6, 2024",
  },
  {
    id: 4,
    imgurl: "/images/Blog/Democratic.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Democratic Elections and AI",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 20, 2024",
  },
  {
    id: 5,
    imgurl: "/images/Blog/Navigating.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Navigating the Next Frontier: The State of Data Centers in India",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 14, 2024",
  },
  {
    id: 6,
    imgurl: "/images/Blog/aimitigation.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "AI Attack Mitigation",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 7,
    imgurl: "/images/Blog/Intricate.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Intricate world of New age Tech",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 8,
    imgurl: "/images/Blog/TikTok.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "TikTok Banned Reasons",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 9,
    imgurl: "/images/Blog/Cyberspace.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "National Defense in Cyberspace",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 10,
    imgurl: "/images/Blog/AIIntegration.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "AI Integration & What could go wrong",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 11,
    imgurl: "/images/Blog/Linguisticequity.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title:
      "Bridging the Language Divide: The Quest for Linguistic Equity in AI",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 12,
    imgurl: "/images/Blog/Sustainability.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "How Tech can expedite Sustainability",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 13,
    imgurl: "/images/Blog/AIIndia.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "AI for India",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 14,
    imgurl: "/images/Blog/Architectures.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Scalable & Flexible Security Architectures",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 15,
    imgurl: "/images/Blog/EUadopts.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "EU adopts a new AI law",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 16,
    imgurl: "/images/Blog/Mechanisms.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Automated Response Mechanisms",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 17,
    imgurl: "/images/Blog/Crossroads.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Navigating the Crossroads",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 18,
    imgurl: "/images/Blog/Embracing.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Embracing the Hybrid Cloud",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 19,
    imgurl: "images/Blog/GenAI.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Securing the Code in a Gen AI World",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 20,
    imgurl: "images/Blog/Guardian.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "The Guardian Angel in the Cloud",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 21,
    imgurl: "images/Blog/Unleashing.png",
    name: "Cybersecurity",
    nameBgColor: "bg-[#E1EFFE]  text-[#1E429F]",
    title: "Unleashing Creativity & Efficiency",
    icon: "/images/home/man.png",
    subname: "St.Fox",
    text: "Read more",
    date: "May 7, 2024",
  },
  {
    id: 22,
    imgurl: "images/Blog/DigitalWorld.png",
    name: "Executive",
    nameBgColor: "bg-[#FCE8F3]   text-[#99154B]",
    title: "Protecting Our Digital World",
    icon: "/images/home/man.png",
    subname: "Manoj Nair",
    text: "Read more",
    date: "November 7, 2025",
  },
];

export const PROMPT_SECURITY = [
  {
    title: "1. Input Filtering -",
    description:
      "Filter inputs for keywords or indicators of attempted prompt injection. This is similar to input filtering for SQL injection.",
  },
  {
    title: "2. Expected Input Token Count",
    description:
      "For applications where the input is restricted to a defined set of keywords in the application, we should monitor the expected input token count and compare it with the actual input token count. When the deviation is very significant, checks should be done and prevent the model response.",
  },
  {
    title: "3. Avoid short prompts -",
    description: "Short prompts are more guessable and should be avoided.",
  },
  {
    title: "4. Use unique and complex prompts -",
    description:
      "Structure the prompts to make them less guessable. When possible, include domain-specific contents to make it harder to do prompt injection.",
  },
  {
    title:
      "5. Use labels and tags to segregate uploaded content from user prompts -",
    description:
      "Separate and denote where untrusted content is being used using tags or labels to limit their influence on user prompts.",
  },
  {
    title: "6. Prompt chaining -",
    description:
      "Feed output from one model to another model only after verification for prompt injection. This limits the attacker's visibility of the impact of their injected prompt making it more difficult to achieve malicious objectives.",
  },
  {
    title: "7. Least privilege access -",
    description:
      "Restrict the LLM access to only the least level of access necessary for achieving its objectives.",
  },
  {
    title: "8. Segment the LLM infrastructure -",
    description:
      "Treat the LLM as a vulnerable untrusted domain. Segment the LLM infra to restrict lateral movement to the organization’s crown jewels.",
  },
  {
    title: "9. Keep human in loop -",
    description:
      "Maintain final human user control on decision-making processes to avoid excessive agency issues.",
  },
  {
    title: "10. Model inbuilt guardrails and moderation services -",
    description:
      "Use guardrails and moderation services when the foundation model presents these features to avoid undesired behaviors.",
  },
  {
    title: "11. Red Teaming LLMs -",
    description:
      "Conduct red teaming specific to LLMs to test for vulnerabilities like bias, offensive behavior, prompt injections, etc. Engage consultants with expertise in LLM testing for critical public-facing applications leveraging the LLMs.",
  },
];
