import type { MetadataRoute } from "next";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://stfox.com";

const publicRoutes: { url: string; changeFrequency: "weekly" | "monthly" | "yearly"; priority: number }[] = [
  { url: "", changeFrequency: "weekly", priority: 1 },
  { url: "about-us", changeFrequency: "monthly", priority: 0.9 },
  { url: "careers", changeFrequency: "weekly", priority: 0.8 },
  { url: "vigile", changeFrequency: "monthly", priority: 0.8 },
  { url: "privacy-policy", changeFrequency: "yearly", priority: 0.5 },
  { url: "terms-of-use", changeFrequency: "yearly", priority: 0.5 },
  { url: "corporate-sustainability", changeFrequency: "monthly", priority: 0.6 },
  { url: "support", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies", changeFrequency: "weekly", priority: 0.9 },
  { url: "ai-security", changeFrequency: "monthly", priority: 0.8 },
  { url: "cloud-engineering", changeFrequency: "monthly", priority: 0.8 },
  { url: "cloud-security", changeFrequency: "monthly", priority: 0.8 },
  { url: "Compromise-Assessment", changeFrequency: "monthly", priority: 0.8 },
  { url: "data-services", changeFrequency: "monthly", priority: 0.8 },
  { url: "dev-secOps", changeFrequency: "monthly", priority: 0.8 },
  { url: "dlp", changeFrequency: "monthly", priority: 0.8 },
  { url: "dspm", changeFrequency: "monthly", priority: 0.8 },
  { url: "email-security", changeFrequency: "monthly", priority: 0.8 },
  { url: "identity-assessment", changeFrequency: "monthly", priority: 0.8 },
  { url: "incident-response", changeFrequency: "monthly", priority: 0.8 },
  { url: "iso", changeFrequency: "monthly", priority: 0.8 },
  { url: "managed", changeFrequency: "monthly", priority: 0.8 },
  { url: "managed-identity", changeFrequency: "monthly", priority: 0.8 },
  { url: "managed-services", changeFrequency: "monthly", priority: 0.8 },
  { url: "mdr", changeFrequency: "monthly", priority: 0.8 },
  { url: "OptimizeDefenses", changeFrequency: "monthly", priority: 0.8 },
  { url: "privacy-ops", changeFrequency: "monthly", priority: 0.8 },
  { url: "sase", changeFrequency: "monthly", priority: 0.8 },
  { url: "sasecloudsecurity", changeFrequency: "monthly", priority: 0.8 },
  { url: "soc", changeFrequency: "monthly", priority: 0.8 },
  { url: "soc-assessment", changeFrequency: "monthly", priority: 0.8 },
  { url: "soc2", changeFrequency: "monthly", priority: 0.8 },
  { url: "SpecializedService", changeFrequency: "monthly", priority: 0.8 },
  { url: "tpcrm", changeFrequency: "monthly", priority: 0.8 },
  { url: "vapt", changeFrequency: "monthly", priority: 0.8 },
  { url: "vciso", changeFrequency: "monthly", priority: 0.8 },
  { url: "vdpo", changeFrequency: "monthly", priority: 0.8 },
  { url: "vulnerability", changeFrequency: "monthly", priority: 0.8 },
  { url: "csse", changeFrequency: "monthly", priority: 0.7 },
  { url: "clutch-at-a-glance", changeFrequency: "monthly", priority: 0.6 },
  { url: "clutch-infographics", changeFrequency: "monthly", priority: 0.6 },
  { url: "clutch-datasheet", changeFrequency: "monthly", priority: 0.6 },
  { url: "casestudies/AIforindia", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/AIIntegration", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/attack-migitation", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Automatedmechanisms", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Crossroads", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/cybersecurity-concerns", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/democratic-election", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/era-of-ai", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/EUAIlaw", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/guardian-angel", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Hybridcloud", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/intricateworld", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Linguisticequity", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Nationaldefense", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/navigating-frontier", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/prompt-injection", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/protecting-digital-world", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/ScalableSecurity", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Saviynt", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/securing-the-code", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/Sustainability", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/tiktok", changeFrequency: "monthly", priority: 0.7 },
  { url: "casestudies/unleashing-creativity", changeFrequency: "monthly", priority: 0.7 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return publicRoutes.map(({ url, changeFrequency, priority }) => ({
    url: url ? `${BASE_URL}/${url}` : BASE_URL,
    lastModified: new Date(),
    changeFrequency,
    priority,
  }));
}
